# @package _group_

common:
  fp16: false
  log_format: json
  log_interval: 2000

checkpoint:
  save_interval: 3000
  save_interval_updates: 3000
  keep_interval_updates: 1
  no_epoch_checkpoints: false
  best_checkpoint_metric: wer

task:
  _name: audio_pretraining
  data: ???
  normalize: false
  labels: ltr
  sample_rate: 16000
  autoregressive: false

dataset:
  num_workers: 6
  max_tokens: 320000
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: 10000
  validate_interval: 1000
  valid_subset: dev_other

distributed_training:
  ddp_backend: no_c10d
  distributed_world_size: 2

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 1300000
  lr: [0.00005]
  sentence_avg: true
  update_freq: [4]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: wav2vec_ctc
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.65
  mask_channel_prob: 0.25
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 10000
